apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  annotations:
<<<<<<< HEAD:mern-docker/manifests/ingress.yaml
    kubernetes.io/ingress.class: "nginx"
=======
    # Traefik is the default ingress controller in K3s
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-api-prefix@kubernetescrd
>>>>>>> f54b0f789c254e373d12228961c924da2f383f22:k8s/ingress.yaml
spec:
  rules:
  - host: app.sasidatta.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
spec:
  stripPrefix:
    prefixes:
      - /api
