apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-app.frontend.fullname" . }}
  labels:
    {{- include "mern-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "mern-app.frontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mern-app.frontend.fullname" . }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
