apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mern-app.mongo.fullname" . }}-pvc
  labels:
    {{- include "mern-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mongo.persistence.storageClass }}
  storageClassName: {{ .Values.mongo.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.size }}
