{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mern-app.fullname" . }}-backend-ingress
  labels:
    {{- include "mern-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "mern-app.backend.fullname" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "mern-app.frontend.fullname" . }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.port }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNginxNamespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.port }}
{{- end }}
