apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mern-app.mongo.secretName" . }}
  labels:
    {{- include "mern-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.auth.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.auth.password | quote }}
  MONGO_URL: {{ printf "mongodb://%s:%s@%s:%d/mern?authSource=admin" .Values.mongo.auth.username .Values.mongo.auth.password (include "mern-app.mongo.fullname" .) (int .Values.mongo.service.port) | quote }}
