apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs-demo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0830a3b2fc3b97724   # 👈 replace with your EBS ID
    fsType: ext4

