# Education Image: The Ping Tool
FROM alpine:latest

# ENTRYPOINT is the 'Tool' (What it IS)
# We use the executable form [JSON]
ENTRYPOINT ["ping"]

# CMD is the 'Default Argument' (How it starts)
# If no arguments are passed, it pings localhost
CMD ["localhost"]
